In [16]:
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, threshold=50)

In [17]:
import imageio
import json

img_arr = imageio.imread('../data/p1ch4/image-dog/bobby.jpg')
img_arr.shape
s = img_arr.tolist()
# print(s)
# json_file ="file.json"
# json.dump(s,json_file)
# 保存到文件里面
print(img_arr)

/var/folders/91/6hm151d56pj61j9w3qjnbycm0000gn/T/ipykernel_64971/1279462227.py:4: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread('../data/p1ch4/image-dog/bobby.jpg')


[[[ 77  45  22]
  [ 77  45  22]
  [ 78  46  21]
  ...
  [118  78  52]
  [117  77  51]
  [116  76  50]]

 [[ 75  43  20]
  [ 76  44  21]
  [ 77  45  20]
  ...
  [118  78  52]
  [117  77  51]
  [116  76  50]]

 [[ 74  39  17]
  [ 75  40  18]
  [ 77  43  18]
  ...
  [117  80  51]
  [117  78  49]
  [116  77  48]]

 ...

 [[215 165  78]
  [216 166  79]
  [217 167  80]
  ...
  [174 121  51]
  [176 123  53]
  [176 123  53]]

 [[215 165  78]
  [216 166  79]
  [217 167  80]
  ...
  [173 123  54]
  [174 124  55]
  [174 124  55]]

 [[215 165  78]
  [216 166  79]
  [217 167  80]
  ...
  [159 109  40]
  [158 107  41]
  [158 107  41]]]


In [18]:
batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)

In [19]:
# 转化为张量
img = torch.from_numpy(img_arr)
print(img)
# 类似与矩阵转置
out = img.permute(2, 0, 1)
print(out)
arr = [[[1,2],[3,4],[3.1,4.2]],[[4,5],[6,7],[6.1,7.1]],[[7,8],[9,10],[11,12]]]
tss = torch.from_numpy(np.array(arr))
print(tss)
# 0代表块，1代表行，2代表列
a = tss.permute(0,1,2)
print(a)
b= tss.permute(0,2,1)
print(b)
c= tss.permute(2,1,0)
print(c)
d=tss.permute(2,0,1)
print(d)
e=tss.permute(1,2,0)
print(e)
# 交换块和行
f=tss.permute(1,0,2)
print(f)

tensor([[[ 77,  45,  22],
         [ 77,  45,  22],
         ...,
         [117,  77,  51],
         [116,  76,  50]],

        [[ 75,  43,  20],
         [ 76,  44,  21],
         ...,
         [117,  77,  51],
         [116,  76,  50]],

        ...,

        [[215, 165,  78],
         [216, 166,  79],
         ...,
         [174, 124,  55],
         [174, 124,  55]],

        [[215, 165,  78],
         [216, 166,  79],
         ...,
         [158, 107,  41],
         [158, 107,  41]]], dtype=torch.uint8)
tensor([[[ 77,  77,  ..., 117, 116],
         [ 75,  76,  ..., 117, 116],
         ...,
         [215, 216,  ..., 174, 174],
         [215, 216,  ..., 158, 158]],

        [[ 45,  45,  ...,  77,  76],
         [ 43,  44,  ...,  77,  76],
         ...,
         [165, 166,  ..., 124, 124],
         [165, 166,  ..., 107, 107]],

        [[ 22,  22,  ...,  51,  50],
         [ 20,  21,  ...,  51,  50],
         ...,
         [ 78,  79,  ...,  55,  55],
         [ 78,  79,  ...,  41,  41

In [20]:
import os

data_dir = '../data/p1ch4/image-cats/'
filenames = [name for name in os.listdir(data_dir)
             if os.path.splitext(name)[-1] == '.png']
# 批量加载图片数据
for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2, 0, 1)
    img_t = img_t[:3] # <1>
    batch[i] = img_t

/var/folders/91/6hm151d56pj61j9w3qjnbycm0000gn/T/ipykernel_64971/3736804637.py:8: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread(os.path.join(data_dir, filename))


In [21]:
batch = batch.float()
# 根据色值最大化原则进行归一化
batch /= 255.0

In [24]:
n_channels = batch.shape[1]
for c in range(n_channels):
    # 求出数据中的均值、标准差
    mean = torch.mean(batch[:, c])
    std = torch.std(batch[:, c])
    batch[:, c] = (batch[:, c] - mean) / std
    print(mean)
    print(std)
    print(batch)

tensor(0.)
tensor(1.)
tensor([[[[ 0.1439,  0.0730,  ...,  0.0198,  0.1794],
          [ 0.4631, -0.2461,  ..., -0.2107, -0.1752],
          ...,
          [-0.3348, -0.3171,  ..., -0.4766, -0.6007],
          [-0.3348, -0.4412,  ..., -0.4766, -0.4944]],

         [[ 0.4632,  0.3874,  ...,  0.3874,  0.6150],
          [ 0.8615,  0.0839,  ...,  0.1408,  0.1787],
          ...,
          [-0.0678, -0.0678,  ..., -0.0489, -0.1816],
          [-0.0678, -0.2006,  ..., -0.0868, -0.0678]],

         [[ 0.7792,  0.6573,  ...,  0.8401,  1.1041],
          [ 1.3072,  0.3933,  ...,  0.5761,  0.6167],
          ...,
          [ 0.3526,  0.3526,  ...,  0.5354,  0.3933],
          [ 0.3323,  0.1495,  ...,  0.4948,  0.5151]]],


        [[[ 0.9595,  0.7999,  ..., -2.3915, -2.4092],
          [ 0.9063,  0.7822,  ..., -2.3738, -2.3738],
          ...,
          [-1.2922, -1.4163,  ..., -1.9837, -1.9660],
          [-1.1149, -0.7958,  ..., -1.9660, -1.9482]],

         [[ 0.6908,  0.4632,  ..., -2.0024, 